### ISSUE TITLE
Stack Canaries Still Exist

### ISSUE THREAD

**Issue by Chris3606** [fmurray1/re_vr#1]
I'm still seeing stack canary checks on my side: upon inspection in IDA, 40129F contains `call @__security_check_cookie@4` and I get a forced termination of the process from that function at runtime if the canary is smashed.  I don't have the source so I'm speculating, but based on our discussion earlier today, is it possible VS 2017 is inserting stack canaries regardless of `-fno-stack-protector-all`?

**Comment by fmurray1** [comment]
should be good now, I had only changed them for debug not release :/

**Comment by Chris3606** [comment]
Yup, looks good now :D
